### ISSUE TITLE
Various Wojak templates

### ISSUE THREAD

**Issue by MollyMaclachlan** [MurdoMaclachlan/ToR-Repost-Collection#14]
This is a hub issue for all the Wojak templates.

https://knowyourmeme.com/memes/wojak

If you have a specific Wojak variant you wish to do, comment below that you're doing it (after checking no one else has done it first).

There are a lot of these, so I'll have difficulty doing them all myself.

**Comment by MollyMaclachlan** [comment]
As a subcategory of this, [Soyjaks vs Chads](https://knowyourmeme.com/memes/soyjaks-vs-chads) is a **high priority**.

**Comment by KomaedaEatsBagels** [comment]
taking care of soyjaks vs chads!

**Comment by KomaedaEatsBagels** [comment]
> taking care of soyjaks vs chads!

I finished this one, though I plan to go through all the Wojaks I'm seeing on Know Your Meme. Should I send them as I go along or just send them all at once?

**Comment by KomaedaEatsBagels** [comment]
progress so far: 

**done:** (18) sojak vs chad/gender variant soy vs chad/grug/norf fc/nujak/pink jak/poljak/pretty princess points/mommy e-thot/bloomer/boomer/consoomer/coomer/doomer/gloomer/soomer/zoomer/daddy's girl/

**to be ID'd:** (9ish) black wojaks/brainlet/classic wojak/i know that feel bro/i want to go home/gun/npc/smug/wither

note:  removed the country jaks because there just isn't a good way to standardize them. there's so many and I haven't encountered one in the wild before lol

**Comment by KomaedaEatsBagels** [comment]
[Wojaks-1.0.zip](https://github.com/MurdoMaclachlan/ToR-Repost-Collection/files/6430654/Wojaks-1.0.zip)

**Comment by KomaedaEatsBagels** [comment]
> [Wojaks-1.0.zip](https://github.com/MurdoMaclachlan/ToR-Repost-Collection/files/6430654/Wojaks-1.0.zip)

here's a collection of 34 different Wojak IDs, separated by type. Each one has an example photo with a similar name, along with a text document that contains the actual ID. If there's any ones I forgot to include, just lmk! feel free to make any changes if some of the descriptions are off
